title: UCLA Physical Sciences Machine Shop
description: Precision instrumentation, design, and fabrication services.
theme: minima
google_analytics:
show_downloads: false

minima:
  nav_pages:
    - index.md
    - equipment.md
    - safety.md
    - contact.md
