title: UCLA Physical Sciences Machine Shop
description: Precision instrumentation, design, and fabrication services for the UCLA research community.
theme: minima

# Leave these as "" if you are testing locally. 
# If on GitHub Pages, baseurl should be "/your-repository-name"
url: ""
baseurl: "/Machineshop-TEST"

# Minima configuration
minima:
  social_links: [#] # Removes social icons from footer if not needed

# Build settings
plugins:
  - jekyll-feed
